### ISSUE TITLE
Does libhttp support FreeRTOS+LWIP ?

### ISSUE THREAD

**Issue by kevin0319** [lammertb/libhttp#39]
Hi Lammertb,

I just want to know if libhttp supports FreeRTOS + LWIP environment.
I am trying to make a http server on Zynq 7000 SoC chip and
am using FreeRTOS with LWIP.
Would you mind telling me how to compile and run on FreeRTOS ?
Thank you in advance,

kevin

**Comment by lammertb** [comment]
FreeRTOS is untested.
