### ISSUE TITLE
httplib_option_value_to_int.c hangs in loop (fix provided)

### ISSUE THREAD

**Issue by active-fred** [lammertb/libhttp#52]
The function 'XX_httplib_option_value_to_int()' hangs forever in the while loop.

Here's a possible fix:

@@ -50,6 +50,7 @@ bool XX_httplib_option_value_to_int( const char *value, int *config ) {
 
                val *= 10;
                val += *ptr - '0';
+               ptr++;
        }
 
        if ( *ptr != '\0' ) return true;

**Comment by lammertb** [comment]
Thanks for the fix. I have updated the code based on your proposal.
