### ISSUE TITLE
QNX 6.6 Port Client httplib_connect_websocket_client null

### ISSUE THREAD

**Issue by evilsalvo** [lammertb/libhttp#57]
Hi Mr. Bies I was porting this to QNX 6.6,7.0... the websocket server functionality works great! Thanks!

 (I am able to communicate via the browser as a client),  but I would like a websocket client in a process.

I modified the websocket client code (examples\websocket_client)
 to work with the latest (Latest commit bb25779 on Aug 15)

However using the client code specifically to create a connection always returns null, and the 
server logs/error handler is enabled  with the full debugging mode and I get no error on the server side indicating what the trouble is.

(Note I removed the websocket server embedded in the example ((examples\websocket_client)) , and have libHTTP server running listening on port 1339.

Here are the arguments for httplib_connect_websocket_client:

	newconn1 = httplib_connect_websocket_client(ctx,"127.0.0.1",atoi("1339"),0,"/websocket",NULL,websocket_client_data_handler,websocket_client_close_handler,&client1_data);

	if (newconn1 == NULL) {
           printf("newconn1 httplib_connect_websocket_client() unknown:%s\n");
	   return 1;
	}

Is there anything else I'm missing? Does ctx have to be initialized with httplib_create_client_context?

Thanks

**Comment by mvsrivas** [comment]
I am also unable to verify the client functionality, could you  please let me know any solution on this

**Comment by lammertb** [comment]
QNX will not be supported. They refuse to answer my requests for a free license to port my open source libraries to QNX. And I am not willing to pay 5000 dollar for a license to develop something which benefits them but doesn't bring me any money.

QNX will only be considered again if someone is willing to pay a perpetual license for me.

**Comment by evilsalvo** [comment]
I feel that
