### ISSUE TITLE
memory leakage found in options 

### ISSUE THREAD

**Issue by pswarfound** [lammertb/libhttp#71]
file: httplib_free_config_options.c
function: XX_httplib_free_config_options
description:
ctx->cgi_pattern should be free but not

**Comment by lammertb** [comment]
Thanks, I will look into this and fix it when it indeed leaks memory.

**Comment by lammertb** [comment]
Fixed with https://github.com/lammertb/libhttp/commit/b87bb0595081f423da3ced292327e8ba6fe86439
